title : Blog
tagline: tagline
author :
  name : name?
  email : email?
  github : ryan.jin
  twitter : 
  feedburner : 

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
